In [74]:
import boto3
import pandas as pd
from io import StringIO

In [75]:
s3 = boto3.resource('s3')
bucket = s3.Bucket('deutsche-boerse-xetra-pds')

In [76]:
bucket_obj1 = bucket.objects.filter(Prefix ='2021-03-15')
bucket_obj2 = bucket.objects.filter(Prefix ='2021-03-16')
objects = [obj for obj in bucket_obj1] + [obj for obj in bucket_obj2]

In [77]:
objects

[s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR00.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR01.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR02.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR03.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR04.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR05.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR06.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR07.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR08.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR09.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR10.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR11.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR12.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR13.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR14.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR15.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR16.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR17.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR18.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR19.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR20.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR21.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR22.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-15/2021-03-15_BINS_XETR23.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR00.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR01.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR02.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR03.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR04.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR05.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR06.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR07.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR08.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR09.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR10.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR11.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR12.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR13.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR14.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR15.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR16.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR17.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR18.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR19.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR20.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR21.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR22.csv'),
 s3.ObjectSummary(bucket_name='deutsche-boerse-xetra-pds', key='2021-03-16/2021-03-16_BINS_XETR23.csv')]

In [78]:
csv_obj_init = bucket.Object(key=objects[0].key).get().get('Body').read().decode('utf-8')
data = StringIO(csv_obj_init)
df_init = pd.read_csv(data, delimiter=',')

In [79]:
df_init.columns

Index(['ISIN', 'Mnemonic', 'SecurityDesc', 'SecurityType', 'Currency',
       'SecurityID', 'Date', 'Time', 'StartPrice', 'MaxPrice', 'MinPrice',
       'EndPrice', 'TradedVolume', 'NumberOfTrades'],
      dtype='object')

In [80]:
df_all = pd.DataFrame(columns=df_init.columns)
for obj in objects:
    csv_obj = bucket.Object(key=obj.key).get().get('Body').read().decode('utf-8') 
    data = StringIO(csv_obj)
    df = pd.read_csv(data, delimiter=',')
    df_all = df_all.append(df)

/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)

/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)
/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/182647221.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)

In [81]:
columns = ['ISIN', 'Date', 'Time', 'StartPrice', 'MaxPrice', 'MinPrice', 'EndPrice', 'TradedVolume']

In [82]:
df_all = df_all.loc[:,columns]
df_all

,ISIN,Date,Time,StartPrice,MaxPrice,MinPrice,EndPrice,TradedVolume
0,AT0000A0E9W5,2021-03-15,08:00,22.12,22.12,22.12,22.12,1527
1,DE000A0DJ6J9,2021-03-15,08:00,53.85,53.85,53.5,53.5,508
2,DE000A0D6554,2021-03-15,08:00,22.24,22.24,22.18,22.18,5270
3,DE000A0D9PT0,2021-03-15,08:00,201.5,201.5,200.6,200.6,1744
4,DE000A0HN5C6,2021-03-15,08:00,38.95,39.06,38.89,39.05,28662
...,...,...,...,...,...,...,...,...
11074,DE000A0WMPJ6,2021-03-16,16:42,19.235,19.235,19.235,19.235,211
11075,DE0007164600,2021-03-16,16:43,103.02,103.02,103.02,103.02,20
11076,DE0007568578,2021-03-16,16:44,24.55,24.55,24.55,24.55,130
11077,DE0007664005,2021-03-16,16:44,266.6,266.6,266.6,266.6,500
11078,DE000A0TGJ55,2021-03-16,16:44,128.0,128.0,128.0,128.0,3

In [83]:
df_all.dropna(inplace=True)

In [84]:
df_all.shape

(206912, 8)

## Get opening price per ISIN per day

In [87]:
df_all['opening_price'] = df_all.sort_values(by=['Time']).groupby(['ISIN','Date'])['StartPrice'].transform('first')

/var/folders/4v/b9_dnv_979d5q6x_smcr82j40000gn/T/ipykernel_8471/1815636015.py:1: FutureWarning: reindexing with a non-unique Index is deprecated and will raise in a future version.
  df_all['opening_price'] = df_all.sort_values(by=['Time']).groupby(['ISIN','Date'])['StartPrice'].transform('first')

ValueError: cannot reindex on an axis with duplicate labels

In [88]:
df_all[df_all.index.duplicated()]

,ISIN,Date,Time,StartPrice,MaxPrice,MinPrice,EndPrice,TradedVolume
0,AT00000FACC2,2021-03-15,09:00,9.38,9.38,9.38,9.38,3
1,CA0679011084,2021-03-15,09:00,17.144,17.144,17.144,17.144,470
2,CA32076V1031,2021-03-15,09:00,14.082,14.082,14.082,14.082,2
3,CA9628791027,2021-03-15,09:00,32.84,32.84,32.84,32.84,2
4,CA98462Y1007,2021-03-15,09:00,3.776,3.776,3.776,3.776,5
...,...,...,...,...,...,...,...,...
11074,DE000A0WMPJ6,2021-03-16,16:42,19.235,19.235,19.235,19.235,211
11075,DE0007164600,2021-03-16,16:43,103.02,103.02,103.02,103.02,20
11076,DE0007568578,2021-03-16,16:44,24.55,24.55,24.55,24.55,130
11077,DE0007664005,2021-03-16,16:44,266.6,266.6,266.6,266.6,500
11078,DE000A0TGJ55,2021-03-16,16:44,128.0,128.0,128.0,128.0,3

In [86]:
df_all
df_all[df_all['ISIN'] == 'AT0000A0E9W5']

,ISIN,Date,Time,StartPrice,MaxPrice,MinPrice,EndPrice,TradedVolume
0,AT0000A0E9W5,2021-03-15,08:00,22.12,22.12,22.12,22.12,1527
4830,AT0000A0E9W5,2021-03-15,08:12,22.24,22.28,22.22,22.28,1914
5714,AT0000A0E9W5,2021-03-15,08:16,22.32,22.36,22.32,22.36,780
6336,AT0000A0E9W5,2021-03-15,08:19,22.32,22.32,22.3,22.3,568
6714,AT0000A0E9W5,2021-03-15,08:20,22.26,22.26,22.26,22.26,250
...,...,...,...,...,...,...,...,...
6670,AT0000A0E9W5,2021-03-16,16:26,22.6,22.6,22.6,22.6,1177
6956,AT0000A0E9W5,2021-03-16,16:27,22.62,22.62,22.56,22.56,1616
7225,AT0000A0E9W5,2021-03-16,16:28,22.58,22.58,22.58,22.58,15
7529,AT0000A0E9W5,2021-03-16,16:29,22.58,22.58,22.56,22.58,251
8044,AT0000A0E9W5,2021-03-16,16:35,22.56,22.56,22.56,22.56,15676